// <auto-generated />
using System;
using KVATUM_CHATFLOW_SERVICE.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KVATUM_CHATFLOW_SERVICE.Infrastructure.Migrations
{
    [DbContext(typeof(ServerFlowDbContext))]
    [Migration("20241214113107_table_WorkspaceChat")]
    partial class table_WorkspaceChat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatWorkspace", b =>
                {
                    b.Property<Guid>("ChatsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspacesId")
                        .HasColumnType("uuid");

                    b.HasKey("ChatsId", "WorkspacesId");

                    b.HasIndex("WorkspacesId");

                    b.ToTable("ChatWorkspace");
                });

            modelBuilder.Entity("KVATUM_CHATFLOW_SERVICE.Core.Entities.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("KVATUM_CHATFLOW_SERVICE.Core.Entities.Models.Hub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Hubs");
                });

            modelBuilder.Entity("KVATUM_CHATFLOW_SERVICE.Core.Entities.Models.HubJoiningInvitation", b =>
                {
                    b.Property<Guid>("HubId")
                        .HasColumnType("uuid");

                    b.Property<string>("HashInvitation")
                        .HasColumnType("text");

                    b.HasKey("HubId", "HashInvitation");

                    b.HasIndex("HubId")
                        .IsUnique();

                    b.ToTable("HubJoiningInvitations");
                });

            modelBuilder.Entity("KVATUM_CHATFLOW_SERVICE.Core.Entities.Models.HubMember", b =>
                {
                    b.Property<Guid>("HubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.HasKey("HubId", "MemberId");

                    b.ToTable("HubMembers");
                });

            modelBuilder.Entity("KVATUM_CHATFLOW_SERVICE.Core.Entities.Models.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HubId")
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("HubId");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("KVATUM_CHATFLOW_SERVICE.Core.Entities.Models.WorkspaceChat", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkspaceId", "ChatId");

                    b.HasIndex("ChatId");

                    b.ToTable("WorkspaceChats");
                });

            modelBuilder.Entity("ChatWorkspace", b =>
                {
                    b.HasOne("KVATUM_CHATFLOW_SERVICE.Core.Entities.Models.Chat", null)
                        .WithMany()
                        .HasForeignKey("ChatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KVATUM_CHATFLOW_SERVICE.Core.Entities.Models.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KVATUM_CHATFLOW_SERVICE.Core.Entities.Models.HubJoiningInvitation", b =>
                {
                    b.HasOne("KVATUM_CHATFLOW_SERVICE.Core.Entities.Models.Hub", "Hub")
                        .WithOne("HubJoiningInvitation")
                        .HasForeignKey("KVATUM_CHATFLOW_SERVICE.Core.Entities.Models.HubJoiningInvitation", "HubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("KVATUM_CHATFLOW_SERVICE.Core.Entities.Models.HubMember", b =>
                {
                    b.HasOne("KVATUM_CHATFLOW_SERVICE.Core.Entities.Models.Hub", "Hub")
                        .WithMany("Members")
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("KVATUM_CHATFLOW_SERVICE.Core.Entities.Models.Workspace", b =>
                {
                    b.HasOne("KVATUM_CHATFLOW_SERVICE.Core.Entities.Models.Hub", "Hub")
                        .WithMany("Workspaces")
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("KVATUM_CHATFLOW_SERVICE.Core.Entities.Models.WorkspaceChat", b =>
                {
                    b.HasOne("KVATUM_CHATFLOW_SERVICE.Core.Entities.Models.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("KVATUM_CHATFLOW_SERVICE.Core.Entities.Models.Hub", b =>
                {
                    b.Navigation("HubJoiningInvitation")
                        .IsRequired();

                    b.Navigation("Members");

                    b.Navigation("Workspaces");
                });
#pragma warning restore 612, 618
        }
    }
}
