version: '3.8'

services:
  kvatum-chat-flow-service:
    image: kvatum-chatflow-service
    restart: always
    ports:
      - "8080:80"
    depends_on:
      kvatum-chat-flow-db:
        condition: service_started
      kvatum-rabbitmq-service:
        condition: service_healthy
    environment:
      - CHAT_FLOW_DB_CONNECTION_STRING=Host=${CHAT_FLOW_DB_HOST};Port=5432;Database=${CHAT_FLOW_DB_DATABASE};Username=${CHAT_FLOW_DB_USERNAME};Password=${CHAT_FLOW_DB_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - HOST=${HOST}

      - JWT_AUTH_SECRET=${JWT_AUTH_SECRET}
      - JWT_AUTH_ISSUER=${JWT_AUTH_ISSUER}
      - JWT_AUTH_AUDIENCE=${JWT_AUTH_AUDIENCE}

      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

