version: '3.8'

services:
  kvatum-chat-flow-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${CHAT_FLOW_DB_USERNAME}
      - POSTGRES_PASSWORD=${CHAT_FLOW_DB_PASSWORD}
      - POSTGRES_DB=${CHAT_FLOW_DB_DATABASE}
    ports:
      - "5435:5432"
    volumes:
      - kvatum-chat-flow-data:/var/lib/postgresql/data