version: '3.8'

services:
  kvatum-email-service:
    image: kvatum-email-service
    restart: always
    ports:
      - "8934:80"
    depends_on:
      kvatum-rabbitmq-service:
        condition: service_healthy

    environment:
      - JWT_AUTH_SECRET=${JWT_AUTH_SECRET}
      - JWT_AUTH_ISSUER=${JWT_AUTH_ISSUER}
      - JWT_AUTH_AUDIENCE=${JWT_AUTH_AUDIENCE}

      - EMAIL_SENDER_NAME=${EMAIL_SENDER_NAME}
      - EMAIL_SENDER_EMAIL=${EMAIL_SENDER_EMAIL}
      - EMAIL_SMTP_SERVER=${EMAIL_SMTP_SERVER}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_SENDER_PASSWORD=${EMAIL_SENDER_PASSWORD}
      
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}

      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

      - RABBITMQ_SEND_CONFIRMATION_CODE_QUEUE_NAME=${RABBITMQ_SEND_CONFIRMATION_CODE_QUEUE_NAME}