version: '3.8'


services:
  kvatum-redis-service: 
    image: redis:latest
    restart: always
    ports:
      - "6979:6379"
    hostname: kvatum-redis-service
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "ping" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 10s
    volumes:
      - kvatum-redis:/data
