version: '3.8'

services:
  kvatum-streaming-service:
    image: kvatum-streaming-service
    restart: always
    ports:
      - "8092:80"
    depends_on:
      kvatum-rabbitmq-service:
        condition: service_healthy
    environment:
      - JWT_AUTH_SECRET=${JWT_AUTH_SECRET}
      - JWT_AUTH_ISSUER=${JWT_AUTH_ISSUER}
      - JWT_AUTH_AUDIENCE=${JWT_AUTH_AUDIENCE}

      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - AUTH_SERVICE_BASE_URL=${AUTH_SERVICE_BASE_URL}
      - FILE_SERVER_URL=${FILE_SERVER_URL}
      - REDIS_CONNECTION_STRING=${REDIS_CONNECTION_STRING}

      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

      - RABBITMQ_CACHED_ACCOUNT_UPDATE_QUEUE_NAME=${RABBITMQ_CACHED_ACCOUNT_UPDATE_QUEUE_NAME}
      - REDIS_INSTANCE_NAME=${REDIS_INSTANCE_NAME}
